#line 1 "MoveShaderParametersToRootConstantBuffer"
cbuffer _RootShaderParameters
{
}

// DebugHash_9cfe8e42b2ef79f20ca26593325671206143d6b04185f82df000db3ff7cab5ee
#line 1 "__UE_FILENAME_SENTINEL"
RWStructuredBuffer<float4> Vertices : register(u0);
[numthreads(64, 64, 1)] 
void MainCS(uint3 ThreadId : SV_DispatchThreadID, uint3 GroupId : SV_GroupID)
{   
    int x = ThreadId.x;
    int y = ThreadId.y;
    int z = ThreadId.z;
    Vertices[ThreadId.x] = float4(x, y, z, 1);
}
