#pragma once
#include "/Engine/Public/Platform.ush"
#include "LandmassTables.ush"

struct Triangle
{
    float3 vertex1;
    float3 vertex2;
    float3 vertex3;
};

int3 VolumeSize;
int3 ChunkCoords;
uint ChunkSize;

RWStructuredBuffer<Triangle> Triangles; 
RWTexture3D<float> DensityMap;
RWStructuredBuffer<uint> Counter;

float GetDensity(int3 coord)
{
    // Calculate global coordinates within the volume
    uint3 globalCoord = coord + (ChunkCoords * ChunkSize);
    
    // Check bounds
    if (globalCoord.x < 0 || globalCoord.x >= VolumeSize.x ||
        globalCoord.y < 0 || globalCoord.y >= VolumeSize.y ||
        globalCoord.z < 0 || globalCoord.z >= VolumeSize.z)
    {
        return 0.0f; // Outside bounds, return default value
    }
    
    return DensityMap[globalCoord];
}

float3 CoordToWorld(int3 coord)
{
    return coord + (ChunkCoords * ChunkSize);

}

float3 GetInterpolatedVertex(float3 VertA, float3 VertB, float ValueA, float ValueB)
{
    float t = (0 - ValueA) / (ValueB - ValueA);
    float3 VertexPosition = VertA + t * (VertB - VertA);
    
    VertexPosition.z = 0.5f;
    return VertexPosition;
}
// CHANGE THIS THREAD Z VALUE WHEN YOU CHANGE THE HEIGHT OF MESH!!
//Number of vertices
[numthreads(8, 8, 2)]
void FillDensity(uint3 ThreadId: SV_DispatchThreadID, uint3 GroupId : SV_GroupID)
{
    if (ThreadId.z == 1)
    {
        DensityMap[ThreadId] = 1.f;
    }
    else
    {
        DensityMap[ThreadId] = -1.f;
    }
}

// Number of cubes
[numthreads(8, 8, 8)] // Define threads per group
void MarchingCube(uint3 ThreadId : SV_DispatchThreadID, uint3 GroupId : SV_GroupID)
{   

    if (any(ThreadId >= VolumeSize - 1))
    {
        return;
    }
    
    int x = ThreadId.x;
    int y = ThreadId.y;
    int z = ThreadId.z;
    
    //Index for Atomic Counter
    uint Index;
    
    
    // Group Id is the coordinates(0 or 7)
    
    //Vertices[GlobalIndex] = float4(x, y, z, DensityMap[ThreadId]);
    
    //corner position
     
    int3 cornerPos[8];
    float3 WorldCoordinate = CoordToWorld(ThreadId);
    
    cornerPos[0] = WorldCoordinate + int3(0, 0, 0);
    cornerPos[1] = WorldCoordinate + int3(1, 0, 0);
    cornerPos[2] = WorldCoordinate + int3(1, 0, 1);
    cornerPos[3] = WorldCoordinate + int3(0, 0, 1);
    cornerPos[4] = WorldCoordinate + int3(0, 1, 0);
    cornerPos[5] = WorldCoordinate + int3(1, 1, 0);
    cornerPos[6] = WorldCoordinate + int3(1, 1, 1);
    cornerPos[7] = WorldCoordinate + int3(0, 1, 1);
    
    int CubeIndex = 0;
    for (int i = 0; i < 8; i++)
    {
        if (GetDensity(cornerPos[i])  > 0)
        {
            CubeIndex |= (1U << i);
        }
    }
    
    
    if (CubeIndex == 0 || CubeIndex == 255)
    {
        
        //Triangle DummyTri;
        // Get the mid-point between each vertex
        //DummyTri.vertex1 = float3(-1,-1,-1);
        //DummyTri.vertex2 = float3(-1,-1,-1);
        //DummyTri.vertex3 = float3(-1,-1,-1);

        //Triangles[Index] = DummyTri;
        
        return;
    }
     
    for (int j = 0; j < 16; j += 3)
    {
        if (TriangleTable[CubeIndex][j] == -1)
        {
            break;
        }
                
        //First Edge that is intersected
        int edge1 = TriangleTable[CubeIndex][j];
        // Corners for that edge
        int Corner1 = cornerIndexAFromEdge[edge1];
        int Corner2 = cornerIndexBFromEdge[edge1];
        
        int edge2 = TriangleTable[CubeIndex][j + 1];
        int Corner3 = cornerIndexAFromEdge[edge2];
        int Corner4 = cornerIndexBFromEdge[edge2];
        
        int edge3 = TriangleTable[CubeIndex][j + 2];
        int Corner5 = cornerIndexAFromEdge[edge3];
        int Corner6 = cornerIndexBFromEdge[edge3];
        
        Triangle Tri;
        // Get the mid-point between each vertex
        Tri.vertex1 = GetInterpolatedVertex(cornerPos[Corner1], cornerPos[Corner2], DensityMap[cornerPos[Corner1]], DensityMap[cornerPos[Corner2]]);
        Tri.vertex2 = GetInterpolatedVertex(cornerPos[Corner3], cornerPos[Corner4], DensityMap[cornerPos[Corner3]], DensityMap[cornerPos[Corner4]]);
        Tri.vertex3 = GetInterpolatedVertex(cornerPos[Corner5], cornerPos[Corner6], DensityMap[cornerPos[Corner5]], DensityMap[cornerPos[Corner6]]);
        
        InterlockedAdd(Counter[0], 1, Index);
        Triangles[Index] = Tri;
        
    }

}





