#pragma once
#include "/Engine/Public/Platform.ush"
#include "LandmassTables.ush"

struct Triangle
{
    float3 vertex1;
    float3 vertex2;
    float3 vertex3;
};

int3 VolumeSize;
int3 ChunkCoords;
uint ChunkSize;

RWStructuredBuffer<Triangle> Triangles; 
RWTexture3D<float> DensityMap;
RWStructuredBuffer<uint> Counter;

float3 GetInterpolatedVertex(float3 VertA, float3 VertB, float ValueA, float ValueB)
{
    float t = (0 - ValueA) / (ValueB - ValueA);
    float3 VertexPosition = VertA + t * (VertB - VertA);
 
    return VertexPosition + ChunkCoords;
}

//Number of vertices
[numthreads(8, 8, 8)]
void CreateMesh(uint3 ThreadId: SV_DispatchThreadID, uint3 GroupId : SV_GroupID)
{
    int x = ThreadId.x;
    int y = ThreadId.y;
    int z = ThreadId.z;
    bool IsBox = z == 0 || x == 0 || y == 0 || z == 7 || x == 7 || y == 7;
    if (IsBox)
    {
        DensityMap[ThreadId] = 1.f;
    }
    else
    {
        DensityMap[ThreadId] = -1.f;
    }
}

float3 DestructionCenter;
float DestructionRadius;

[numthreads(8, 8, 8)]
void CreateCrater(uint3 ThreadId : SV_DispatchThreadID, uint3 GroupId : SV_GroupID)
{
    
    int x = ThreadId.x;
    int y = ThreadId.y;
    int z = ThreadId.z;
    
    float distance = length(float3(x, y, z) - DestructionCenter);
    
    bool IsCrater = (x > 2 && x < 6) && (y > 2 && y < 6) && z > 2;
    bool IsBox = z == 0 || x == 0 || y == 0 || z == 7 || x == 7 || y == 7;
    
    
    if (IsCrater)
    {
        DensityMap[ThreadId] = 1.f;
    }
    else
    {
        DensityMap[ThreadId] = -1.f;
    }
    
    
    /*
    if (distance < DestructionRadius)
    {
        DensityMap[ThreadId] = 1.f;
    }
    else
    {

        if (IsBox)
        {
            DensityMap[ThreadId] = 1.f;
        }
        else
        {
            DensityMap[ThreadId] = -1.f;
        }
    }
    */
}

// Number of cubes
[numthreads(7, 7, 7)] // Define threads per group
void MarchingCube(uint3 ThreadId : SV_DispatchThreadID, uint3 GroupId : SV_GroupID)
{   
    // Check if the thread is outside the bounds of the volume
    
    int x = ThreadId.x;
    int y = ThreadId.y;
    int z = ThreadId.z;
    
    //Index for Atomic Counter
    uint Index;
    
    //corner position
     
    int3 cornerPos[8];
    /*
    Triangle Tri;
    Tri.vertex1 = WorldCoordinate;
    Tri.vertex2 = WorldCoordinate;
    Tri.vertex3 = WorldCoordinate;
    
    InterlockedAdd(Counter[0], 1, Index);
    Triangles[Index] = Tri;
    */
    cornerPos[0] = ThreadId + int3(0, 0, 0);
    cornerPos[1] = ThreadId + int3(1, 0, 0);
    cornerPos[2] = ThreadId + int3(1, 0, 1);
    cornerPos[3] = ThreadId + int3(0, 0, 1);
    cornerPos[4] = ThreadId + int3(0, 1, 0);
    cornerPos[5] = ThreadId + int3(1, 1, 0);
    cornerPos[6] = ThreadId + int3(1, 1, 1);
    cornerPos[7] = ThreadId + int3(0, 1, 1);
    
    int CubeIndex = 0;
    for (int i = 0; i < 8; i++)
    {
        if (DensityMap[cornerPos[i]]  > 0)
        {
            CubeIndex |= (1U << i);
        }
    }
    
    
    if (CubeIndex == 0 || CubeIndex == 255)
    {
        return;
    }
     
    for (int j = 0; j < 16; j += 3)
    {
        if (TriangleTable[CubeIndex][j] == -1)
        {
            break;
        }
                
        //First Edge that is intersected
        int edge1 = TriangleTable[CubeIndex][j];
        // Corners for that edge
        int Corner1 = cornerIndexAFromEdge[edge1];
        int Corner2 = cornerIndexBFromEdge[edge1];
        
        int edge2 = TriangleTable[CubeIndex][j + 1];
        int Corner3 = cornerIndexAFromEdge[edge2];
        int Corner4 = cornerIndexBFromEdge[edge2];
        
        int edge3 = TriangleTable[CubeIndex][j + 2];
        int Corner5 = cornerIndexAFromEdge[edge3];
        int Corner6 = cornerIndexBFromEdge[edge3];
        
        Triangle Tri;
        // Get the mid-point between each vertex
        
        Tri.vertex1 = GetInterpolatedVertex(cornerPos[Corner1], cornerPos[Corner2], DensityMap[cornerPos[Corner1]], DensityMap[cornerPos[Corner2]]);
        Tri.vertex2 = GetInterpolatedVertex(cornerPos[Corner3], cornerPos[Corner4], DensityMap[cornerPos[Corner3]], DensityMap[cornerPos[Corner4]]);
        Tri.vertex3 = GetInterpolatedVertex(cornerPos[Corner5], cornerPos[Corner6], DensityMap[cornerPos[Corner5]], DensityMap[cornerPos[Corner6]]);
        
        
        InterlockedAdd(Counter[0], 1, Index);
        Triangles[Index] = Tri;
        
    }

}

// Test Shader
RWStructuredBuffer<float3> TestBuffer;
RWStructuredBuffer<uint> TestCounter;
int3 ChunkLocation;

[numthreads(4, 4, 1)] // Define threads per group
void TestShader(uint3 ThreadId : SV_DispatchThreadID, uint3 GroupId : SV_GroupID)
{
    uint GlobalIndex;
    InterlockedAdd(TestCounter[0], 1, GlobalIndex);
    
    TestBuffer[GlobalIndex] = ChunkLocation + ThreadId;
}




