#pragma once

#include "CoreMinimal.h"
#include "RenderResource.h"
#include "ShaderParameters.h"
#include "RHIResources.h"
#include "StaticMeshResources.h"
#include "LandmassGeneration/Shaders/GrassComputeShader.h"

/**
 * Class to handle the rendering of grass instances created by the compute shader
 */
class FGrassRenderer : public FRenderResource
{
public:
    FGrassRenderer();
    virtual ~FGrassRenderer();

    // Initialize the renderer with a static mesh
    void Initialize(UStaticMesh* InGrassMesh, UMaterialInterface* InGrassMaterial, int32 InMaxInstances);

    // FRenderResource interface
    virtual void InitRHI() override;
    virtual void ReleaseRHI() override;

    // Update the renderer with new parameters
    void UpdateParameters(const FGrassShaderParameters& InParameters);

    // Execute the compute shader to generate grass instances
    void GenerateGrassInstances(FRHICommandListImmediate& RHICmdList);

    // Render the grass instances
    void RenderGrass(const FSceneView* View, FRHICommandList& RHICmdList);

    // Get the number of instances rendered in the last frame
    uint32 GetInstanceCount() const { return InstanceCount; }

    // Get the maximum number of instances
    uint32 GetMaxInstances() const { return MaxInstances; }

private:
    // Static mesh to use for grass
    UStaticMesh* GrassMesh;

    // Material to use for grass
    UMaterialInterface* GrassMaterial;

    // Number of instances to render
    uint32 InstanceCount;

    // Maximum number of instances
    uint32 MaxInstances;

    // Instance buffer for the grass transforms
    FBufferRHIRef InstanceBuffer;
    FShaderResourceViewRHIRef InstanceBufferSRV;
    FUnorderedAccessViewRHIRef InstanceBufferUAV;

    // Counter buffer for the number of instances
    FBufferRHIRef CounterBuffer;
    FUnorderedAccessViewRHIRef CounterBufferUAV;

    // Buffer to read back instance count
    TSharedPtr<FRHIGPUBufferReadback> CounterReadback;

    // Shader parameters
    FGrassShaderParameters Parameters;

    // Vertex factory for instanced rendering
    FLocalVertexFactory VertexFactory;

    // Vertex buffer declarations
    FStaticMeshVertexBuffers VertexBuffers;

    // Resource initialized flag
    bool bResourcesInitialized;
};

/**
 * Component to handle rendering the grass generated by the compute shader
 */
class FGrassComponent
{
public:
    FGrassComponent();
    ~FGrassComponent();

    // Initialize with grass mesh and material
    void Initialize(UStaticMesh* InGrassMesh, UMaterialInterface* InGrassMaterial, int32 InMaxInstances);

    // Release resources
    void Release();

    // Update parameters
    void UpdateParameters(const FGrassShaderParameters& InParameters);

    // Generate grass instances
    void GenerateGrassInstances(FRHICommandListImmediate& RHICmdList);

    // Is the component valid and ready to render?
    bool IsValid() const;

    // Get the grass renderer
    FGrassRenderer* GetRenderer() { return &Renderer; }

private:
    // Grass renderer
    FGrassRenderer Renderer;

    // Is the component initialized?
    bool bInitialized;
};